# Scraping data from 2022

In [20]:
import pandas as pd
from datetime import date
from bs4 import BeautifulSoup
import requests
from playwright.async_api import async_playwright
import time
import numpy as np
pd.set_option('display.max_colwidth', None)

In [21]:
dates = ["01.12.2022", "02.12.2022"]
#dates = ["01.12.2022", "02.12.2022", "03.12.2022", "04.12.2022", "05.12.2022", "06.12.2022", "07.12.2022", "08.12.2022", "09.12.2022", "10.12.2022", "11.12.2022", "12.12.2022", "13.12.2022", "14.12.2022", "15.12.2022", "16.12.2022", "17.12.2022", "18.12.2022", "19.12.2022", "20.12.2022", "21.12.2022", "22.12.2022", "23.12.2022", "24.12.2022", "25.12.2022", "26.12.2022", "27.12.2022", "28.12.2022", "29.12.2022", "30.12.2022", "31.12.2022", "01.01.2023", "02.01.2023", "03.01.2023", "04.01.2023"]

In [22]:
df = pd.read_csv("data/links.csv")

total_df = pd.DataFrame()
df.head(20)

,country,area,link
0,Albania,BZN AL,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YAL-KESH-----5!BZN|10YAL-KESH-----5&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
1,Austria,BZN AT,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YAT-APG------L!BZN|10YAT-APG------L&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
2,Austria,BZN DE-AT-LU,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YAT-APG------L!BZN|10Y1001A1001A63L&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
3,Belgium,BZN BE,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YBE----------2!BZN|10YBE----------2&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
4,Bosnia and Herzegovenia,BZN BA,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YBA-JPCC-----D!BZN|10YBA-JPCC-----D&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
5,Bulgaria,BZN BG,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YCA-BULGARIA-R!BZN|10YCA-BULGARIA-R&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
6,Croatia,BZN HR,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YHR-HEP------M!BZN|10YHR-HEP------M&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
7,Cyprus,BZN CY,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YCY-1001A0003J!BZN|10YCY-1001A0003J&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
8,Czech Republic,BZN CZ,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YCZ-CEPS-----N!BZN|10YCZ-CEPS-----N&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
9,Czech Republic,BZN CZ-DE-SK,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YCZ-CEPS-----N!BZN|10YDOM-CZ-DE-SKK&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
10,Denmark,BZN DK1,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A65H!BZN|10YDK-1--------W&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
11,Denmark,BZN DK2,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A65H!BZN|10YDK-2--------M&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
12,Estonia,BZN EE,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A39I!BZN|10Y1001A1001A39I&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
13,Finland,BZN FI,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YFI-1--------U!BZN|10YFI-1--------U&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
14,France,BZN FR,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YFR-RTE------C!BZN|10YFR-RTE------C&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
15,Georgia,BZN GE,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001B012!BZN|10Y1001A1001B012&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
16,Germany,BZN DE-LU,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A83F!BZN|10Y1001A1001A82H&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
17,Germany,BZN CZ-DE-SK,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A83F!BZN|10YDOM-CZ-DE-SKK&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
18,Germany,BZN DE-AT-LU,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A83F!BZN|10Y1001A1001A63L&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
19,Greece,BZN GR,https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2023+00:00|CET|DAY&biddingZone.values=CTY|10YGR-HTSO-----Y!BZN|10YGR-HTSO-----Y&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

In [23]:
playwright = await async_playwright().start()
browser = await playwright.chromium.launch(headless = False)
page = await browser.new_page()

url = df.iloc[0]['link']
await page.goto(url)

time.sleep(1)
await page.locator("#close-button").click()

In [24]:
for date in dates:
    df = df.replace(to_replace=r'\d\d.\d\d.202\d', value= date, regex=True)

    for index, row in df.iterrows():
        url = row['link']

        country = row['country']
        area = row['area']
    
        await page.goto(url)

        time.sleep(1)

        tables = pd.read_html(await page.content(), flavor = 'html5lib')
        data = tables[0]
        data.insert(0, 'date', date)
        data.insert(1, 'country', country)
        data.insert(2, 'area', area)
        total_df = pd.concat([total_df, data], axis=0)
    
    print("scraped", date)
    print("scraped", url)
total_df

scraped 01.12.2022
scraped https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.12.2022+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A92E!BZN|17Y0000009369493&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
scraped 02.12.2022
scraped https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=02.12.2022+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A92E!BZN|17Y0000009369493&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

          date         country          area            MTU  Day-ahead Price  \
                                                        MTU [Currency / MWh]
0   01.12.2022         Albania        BZN AL  00:00 - 01:00              NaN
1   01.12.2022         Albania        BZN AL  01:00 - 02:00              NaN
2   01.12.2022         Albania        BZN AL  02:00 - 03:00              NaN
3   01.12.2022         Albania        BZN AL  03:00 - 04:00              NaN
4   01.12.2022         Albania        BZN AL  04:00 - 05:00              NaN
..         ...             ...           ...            ...              ...
19  02.12.2022  United Kingdom  BZN GB(IFA2)  19:00 - 20:00              n/e
20  02.12.2022  United Kingdom  BZN GB(IFA2)  20:00 - 21:00              n/e
21  02.12.2022  United Kingdom  BZN GB(IFA2)  21:00 - 22:00              n/e
22  02.12.2022  United Kingdom  BZN GB(IFA2)  22:00 - 23:00              n/e
23  02.12.2022  United Kingdom  BZN GB(IFA2)  23:00 - 00:00              n/e


   [EUR / MWh]
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
..         ...
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN

[4224 rows x 6 columns]

In [28]:
total_df.columns = ['date','country', 'area', 'mtu', 'price(currency/mwh)', 'price(eur/mwh)']
total_df

# Standardize the missing values
total_df.replace({'-': np.nan}, inplace=True)
total_df.replace({'n/e': np.nan}, inplace=True)

# And reorder the columns
data = total_df[['date', 'country', 'area', 'mtu', 'price(currency/mwh)', 'price(eur/mwh)']]
data.head(50)

,date,country,area,mtu,price(currency/mwh),price(eur/mwh)
0,01.12.2022,Albania,BZN AL,00:00 - 01:00,NaN,NaN
1,01.12.2022,Albania,BZN AL,01:00 - 02:00,NaN,NaN
2,01.12.2022,Albania,BZN AL,02:00 - 03:00,NaN,NaN
3,01.12.2022,Albania,BZN AL,03:00 - 04:00,NaN,NaN
4,01.12.2022,Albania,BZN AL,04:00 - 05:00,NaN,NaN
5,01.12.2022,Albania,BZN AL,05:00 - 06:00,NaN,NaN
6,01.12.2022,Albania,BZN AL,06:00 - 07:00,NaN,NaN
7,01.12.2022,Albania,BZN AL,07:00 - 08:00,NaN,NaN
8,01.12.2022,Albania,BZN AL,08:00 - 09:00,NaN,NaN
9,01.12.2022,Albania,BZN AL,09:00 - 10:00,NaN,NaN
10,01.12.2022,Albania,BZN AL,10:00 - 11:00,NaN,NaN
11,01.12.2022,Albania,BZN AL,11:00 - 12:00,NaN,NaN
12,01.12.2022,Albania,BZN AL,12:00 - 13:00,NaN,NaN
13,01.12.2022,Albania,BZN AL,13:00 - 14:00,NaN,NaN
14,01.12.2022,Albania,BZN AL,14:00 - 15:00,NaN,NaN
15,01.12.2022,Albania,BZN AL,15:00 - 16:00,NaN,NaN
16,01.12.2022,Albania,BZN AL,16:00 - 17:00,NaN,NaN
17,01.12.2022,Albania,BZN AL,17:00 - 18:00,NaN,NaN
18,01.12.2022,Albania,BZN AL,18:00 - 19:00,NaN,NaN
19,01.12.2022,Albania,BZN AL,19:00 - 20:00,NaN,NaN
20,01.12.2022,Albania,BZN AL,20:00 - 21:00,NaN,NaN
21,01.12.2022,Albania,BZN AL,21:00 - 22:00,NaN,NaN
22,01.12.2022,Albania,BZN AL,22:00 - 23:00,NaN,NaN
23,01.12.2022,Albania,BZN AL,23:00 - 00:00,NaN,NaN
0,01.12.2022,Austria,BZN AT,00:00 - 00:15,NaN,370.00
1,01.12.2022,Austria,BZN AT,00:15 - 00:30,NaN,370.00
2,01.12.2022,Austria,BZN AT,00:30 - 00:45,NaN,236.07
3,01.12.2022,Austria,BZN AT,00:45 - 01:00,NaN,221.77
4,01.12.2022,Austria,BZN AT,01:00 - 01:15,NaN,408.34
5,01.12.2022,Austria,BZN AT,01:15 - 01:30,NaN,300.00
6,01.12.2022,Austria,BZN AT,01:30 - 01:45,NaN,228.93
7,01.12.2022,Austria,BZN AT,01:45 - 02:00,NaN,217.17
8,01.12.2022,Austria,BZN AT,02:00 - 02:15,NaN,370.00
9,01.12.2022,Austria,BZN AT,02:15 - 02:30,NaN,307.86
10,01.12.2022,Austria,BZN AT,02:30 - 02:45,NaN,241.16
11,01.12.2022,Austria,BZN AT,02:45 - 03:00,NaN,230.58
12,01.12.2022,Austria,BZN AT,03:00 - 03:15,NaN,225.64
13,01.12.2022,Austria,BZN AT,03:15 - 03:30,NaN,228.43
14,01.12.2022,Austria,BZN AT,03:30 - 03:45,NaN,300.00
15,01.12.2022,Austria,BZN AT,03:45 - 04:00,NaN,331.52
16,01.12.2022,Austria,BZN AT,04:00 - 04:15,NaN,69.67
17,01.12.2022,Austria,BZN AT,04:15 - 04:30,NaN,222.20
18,01.12.2022,Austria,BZN AT,04:30 - 04:45,NaN,370.00
19,01.12.2022,Austria,BZN AT,04:45 - 05:00,NaN,448.86
20,01.12.2022,Austria,BZN AT,05:00 - 05:15,NaN,35.00
21,01.12.2022,Austria,BZN AT,05:15 - 05:30,NaN,256.00
22,01.12.2022,Austria,BZN AT,05:30 - 05:45,NaN,454.14
23,01.12.2022,Austria,BZN AT,05:45 - 06:00,NaN,474.87
24,01.12.2022,Austria,BZN AT,06:00 - 06:15,NaN,-5.12
25,01.12.2022,Austria,BZN AT,06:15 - 06:30,NaN,427.84

In [29]:
data = data.drop(['price(currency/mwh)'], axis=1)
data

          date         country          area            mtu  price(eur/mwh)
0   01.12.2022         Albania        BZN AL  00:00 - 01:00             NaN
1   01.12.2022         Albania        BZN AL  01:00 - 02:00             NaN
2   01.12.2022         Albania        BZN AL  02:00 - 03:00             NaN
3   01.12.2022         Albania        BZN AL  03:00 - 04:00             NaN
4   01.12.2022         Albania        BZN AL  04:00 - 05:00             NaN
..         ...             ...           ...            ...             ...
19  02.12.2022  United Kingdom  BZN GB(IFA2)  19:00 - 20:00             NaN
20  02.12.2022  United Kingdom  BZN GB(IFA2)  20:00 - 21:00             NaN
21  02.12.2022  United Kingdom  BZN GB(IFA2)  21:00 - 22:00             NaN
22  02.12.2022  United Kingdom  BZN GB(IFA2)  22:00 - 23:00             NaN
23  02.12.2022  United Kingdom  BZN GB(IFA2)  23:00 - 00:00             NaN

[4224 rows x 5 columns]

In [27]:
data.to_csv("data/prices-hourly-011222-050123.csv", index=True)

In [34]:
#data_day = round(data.groupby(['date','country'])['price(eur/mwh)'].mean())
data_day = round(data.groupby(['date', 'country']).agg({'price(eur/mwh)': 'mean'}))

# Reset the index to get the date on each row.
data_day = data_day.reset_index()
data_day

          date                  country  price(eur/mwh)
0   01.12.2022                  Albania             NaN
1   01.12.2022                  Austria           399.0
2   01.12.2022                  Belgium           388.0
3   01.12.2022  Bosnia and Herzegovenia             NaN
4   01.12.2022                 Bulgaria           330.0
..         ...                      ...             ...
75  02.12.2022                   Sweden           332.0
76  02.12.2022              Switzerland           395.0
77  02.12.2022                   Turkey             NaN
78  02.12.2022                  Ukraine             NaN
79  02.12.2022           United Kingdom             NaN

[80 rows x 3 columns]